// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlfzWQ5UmHKByLeSo1Me5TYfTom9jwF1E',
    appId: '1:918927223377:android:0175204d3b09ce8ec82670',
    messagingSenderId: '918927223377',
    projectId: 'kasirbanimasum',
    storageBucket: 'kasirbanimasum.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHVZ4cSCifSTZHFqjmLORfncOshzDl7Xw',
    appId: '1:918927223377:web:b0507475cf1ea581c82670',
    messagingSenderId: '918927223377',
    projectId: 'kasirbanimasum',
    authDomain: 'kasirbanimasum.firebaseapp.com',
    storageBucket: 'kasirbanimasum.firebasestorage.app',
    measurementId: 'G-HH1CF3HF32',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVZ4cSCifSTZHFqjmLORfncOshzDl7Xw',
    appId: '1:918927223377:web:67fb749031d81dc6c82670',
    messagingSenderId: '918927223377',
    projectId: 'kasirbanimasum',
    authDomain: 'kasirbanimasum.firebaseapp.com',
    storageBucket: 'kasirbanimasum.firebasestorage.app',
    measurementId: 'G-6HT48DL7CX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRAsJk953XhJYCJMGRr5bK0DIcR4tp540',
    appId: '1:918927223377:ios:0073e579a10d2c19c82670',
    messagingSenderId: '918927223377',
    projectId: 'kasirbanimasum',
    storageBucket: 'kasirbanimasum.firebasestorage.app',
    iosBundleId: 'com.example.belajarProvider',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRAsJk953XhJYCJMGRr5bK0DIcR4tp540',
    appId: '1:918927223377:ios:0073e579a10d2c19c82670',
    messagingSenderId: '918927223377',
    projectId: 'kasirbanimasum',
    storageBucket: 'kasirbanimasum.firebasestorage.app',
    iosBundleId: 'com.example.belajarProvider',
  );

}